name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install required Python dependencies

      # Step 4: Run the tests
      - name: Run tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          python -m unittest discover -s tests  # This runs the tests in the tests directory
