name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to latest version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Install dependencies

      - name: Check current directory
        run: pwd

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests -p "test_*.py"  # Run tests from 'tests' directory
